import localFont from "next/font/local";
import "./globals.css";

const worksans = localFont({
  src: [
    {
      path: '../public/fonts/WorkSans-Regular.ttf',
      weight: '400'
    },
    {
      path: '../public/fonts/WorkSans-SemiBold.ttf',
      weight: '700'
    }
  ],
  variable: '--font-worksans'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      </head>
      <body
        className={`${worksans.variable} font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
